[versions]
agp = "9.1.0"
coroutines = "1.10.2"
coreKtx = "1.18.0"
annotation = "1.9.1"

[libraries]
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }